# SITE CONFIGURATION
baseurl: "http://axelnyberg.github.io" # the subpath of your site, e.g. /blog/
url: "https://axelnyberg.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Axel Nyberg
  avatar: "axel.jpg"
  gravatar: # Email MD5 hash
  description: "This basic website is my portfolio." # used by search engines

  # Header and footer text
  header_text: >
    <p>Welcome! Take a look at my portfolio.</p>
  header_text_feature_image:
  footer_text: >
 
   <img src="https://axelnyberg.github.io/favicon.png" style="width:304px;height:228px;">

  # Icons
  rss: false
  email_address: "axelnyberg@icloud.com" # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "axelnyberg"
  google_plus:
  instagram:
  linkedin: "https://www.linkedin.com/in/axelnyberg"  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: 
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
